# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "332cb4617693ed6b0861c91a3e943510"
name = "IbiBot"
handle = "aria-3"
application_url = "https://pretty-acquisition-empire-flexible.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pretty-acquisition-empire-flexible.trycloudflare.com/auth/callback",
  "https://pretty-acquisition-empire-flexible.trycloudflare.com/auth/shopify/callback",
  "https://pretty-acquisition-empire-flexible.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[[extensions]]
type = "theme"
name = "Chat Widget"
handle = "chat-widget"
